site_name: AIMES Ecosystem User Guide
site_description: "This is a user guide to use the AIMES Ecosystem web application."
site_author: "Transport Technologies - University of Melbourne"
copyright: "&copy; 2023 University of Melbourne"
theme:
  name: material
  language: "en"
  favicon: images/icon.png
  logo: images/icon.png
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    scheme: slate
    primary: custom
  features:
    - tabs
    - navigation.tabs

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"
      title: "On this page"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "stylesheets/extra.css"
extra:
  manifest: "manifest.json"
  generator: false
  # social:
  #   - icon: "fontawesome/brands/github-alt"
  #     link: "https://github.com/peaceiris"
  #   - icon: "fontawesome/brands/twitter"
  #     link: "https://twitter.com/piris314en"


nav:
  - Home: index.md
  - Getting started:
    - Introduction: getting-started/introduction.md
    - Requesting access: getting-started/requesting-access.md
    - Using the platform: getting-started/using-the-platform.md
  - Concepts:
    - Regions: concepts/regions.md
    - Links and Intersections: concepts/links-and-intersections.md